### ISSUE TITLE
Add fields to the register page (first name, last name, etc)

### ISSUE THREAD

**Issue by jcserv** [collabcloud/project-collabcloud#43]
This should match the edit user profile page (click on the profile picture on the navbar to access this page)

**Comment by matthuynh** [comment]
We should fill out the actual Terms and Conditions too

**Comment by jcserv** [comment]
Ok, adding that as a separate issue

**Comment by matthuynh** [comment]
Also, I think it would be a good idea to have a brief explanation of why we need each field (eg. why we would need a user's name, user's email, etc)
