### ISSUE TITLE
Change Github auth from parashan -> collabcloud

### ISSUE THREAD

**Issue by jcserv** [collabcloud/project-collabcloud#73]

**Comment by matthuynh** [comment]
Important note:

> Deprecation Notice: GitHub will discontinue the OAuth Authorizations API, which is used by integrations to create personal access tokens and OAuth tokens, and you must now create these tokens using our web application flow. The OAuth Authorizations API will be removed on November, 13, 2020. For more information, including scheduled brownouts, see the blog post.

Because of this, I will be following the docs [here](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/), instead of [here](https://developer.github.com/v3/oauth_authorizations/)
